from enum import Enum


# Agent defaults
DEFAULT_MAX_TOKENS = 8192
DEFAULT_TIMEOUT = 300

# Environment variables
REGION_ENV_VAR = "AWS_REGION"
STAGE_ENV_VAR = "AWS_STAGE"
CUSTOMER_CONTAINER_URI_ENV_VAR = "AWS_CUSTOMER_CONTAINER_URI"
MEMORY_ARN_ENV_VAR = "AWS_MEMORY_ARN"
MEMORY_ACTOR_ID_ENV_VAR = "AWS_MEMORY_ACTOR_ID"
TRUNCATION_STRATEGY_ENV_VAR = "AWS_TRUNCATION_STRATEGY"
TRUNCATION_MESSAGES_COUNT_ENV_VAR = "AWS_TRUNCATION_MESSAGES_COUNT"
TRUNCATION_SUMMARY_RATIO_ENV_VAR = "AWS_TRUNCATION_SUMMARY_RATIO"
TRUNCATION_PRESERVE_RECENT_MESSAGES_COUNT_ENV_VAR = "AWS_TRUNCATION_PRESERVE_RECENT_MESSAGES_COUNT"
TRUNCATION_SUMMARIZATION_SYSTEM_PROMPT_ENV_VAR = "AWS_TRUNCATION_SUMMARIZATION_SYSTEM_PROMPT"


# Truncation strategies (values match LoopyServiceModel TruncationStrategy enum)
class TruncationStrategy(str, Enum):
    SLIDING_WINDOW = "sliding_window"
    SUMMARIZATION = "summarization"
    NONE = "none"

# Memory defaults
DEFAULT_ACTOR_ID = "default"

# Container-in-Container (CinC)
FILESYSTEM_MOUNT_PATHS_ENV_VAR = "AWS_FILESYSTEM_MOUNT_PATHS"
CUSTOMER_CONTAINER_NAME = "customer-env"
DEFAULT_CONTAINER_NAME = "default"
CTR_SOCKET = "/run/containerd/containerd.sock"

# Identity header
WORKLOAD_ACCESS_TOKEN_HEADER = "x-amzn-bedrock-agentcore-workload-access-token"
