# generated by datamodel-codegen:
#   filename:  tmp84n51u7v
#   timestamp: 2026-04-22T17:33:37+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field, RootModel, SecretStr


class AccessDeniedException(BaseModel):
    message: Optional[str] = Field(default=None, pattern='^[\\s\\S]+$')


class AccessDeniedExceptionResponseContent(BaseModel):
    message: Optional[str] = Field(default=None, pattern='^[\\s\\S]+$')


class AutomationStreamStatus(str, Enum):
    ENABLED = 'ENABLED'
    DISABLED = 'DISABLED'


class AutomationStreamUpdate(BaseModel):
    streamStatus: Optional[AutomationStreamStatus] = None


class BasicAuth(BaseModel):
    secretArn: str = Field(
        ...,
        pattern='^arn:aws(-[a-z-]+)?:secretsmanager:[a-z0-9-]+:[0-9]{12}:secret:[a-zA-Z0-9/_+=.@-]+$',
    )


class BrowserActionStatus(str, Enum):
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'


class BrowserEnterprisePolicyType(str, Enum):
    MANAGED = 'MANAGED'
    RECOMMENDED = 'RECOMMENDED'


class BrowserProfileConfiguration(BaseModel):
    profileIdentifier: str = Field(
        ..., pattern='^[a-zA-Z][a-zA-Z0-9_]{0,47}-[a-zA-Z0-9]{10}$'
    )


class BrowserSessionStatus(str, Enum):
    READY = 'READY'
    TERMINATED = 'TERMINATED'


class BrowserSessionSummary(BaseModel):
    browserIdentifier: str
    sessionId: str = Field(..., pattern='^[0-9a-zA-Z]{1,40}$')
    name: Optional[str] = Field(default=None, max_length=100, min_length=1)
    status: BrowserSessionStatus
    createdAt: datetime
    lastUpdatedAt: Optional[datetime] = None


class CodeInterpreterSessionStatus(str, Enum):
    READY = 'READY'
    TERMINATED = 'TERMINATED'


class CodeInterpreterSessionSummary(BaseModel):
    codeInterpreterIdentifier: str
    sessionId: str = Field(..., pattern='^[0-9a-zA-Z]{1,40}$')
    name: Optional[str] = Field(default=None, max_length=100, min_length=1)
    status: CodeInterpreterSessionStatus
    createdAt: datetime
    lastUpdatedAt: Optional[datetime] = None


class CodeInterpreterStreamOutput2(BaseModel):
    accessDeniedException: AccessDeniedException


class CommandExecutionStatus(str, Enum):
    COMPLETED = 'COMPLETED'
    TIMED_OUT = 'TIMED_OUT'


class ConflictException(BaseModel):
    message: Optional[str] = Field(default=None, pattern='^[\\s\\S]+$')


class ConflictExceptionResponseContent(BaseModel):
    message: Optional[str] = Field(default=None, pattern='^[\\s\\S]+$')


class ContentBlockType(str, Enum):
    text = 'text'
    image = 'image'
    resource = 'resource'
    resource_link = 'resource_link'


class ContentDeltaEvent(BaseModel):
    stdout: Optional[str] = None
    """
    Standard output content
    """
    stderr: Optional[str] = None
    """
    Standard error content
    """


class ContentStartEvent(BaseModel):
    pass


class ContentStopEvent(BaseModel):
    exitCode: int
    """
    Exit code: 0 = success, -1 = platform error, >0 = command error
    """
    status: CommandExecutionStatus


class DomainPattern(RootModel[str]):
    root: str = Field(
        ...,
        max_length=253,
        min_length=1,
        pattern='^(\\.)?[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?(\\.[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?)*$',
    )


class GetAgentCardOutputPayload(RootModel[Any]):
    root: Any


class GetRuntimeProtectedResourceMetadataResponseContent(BaseModel):
    resource: Optional[str] = None
    """
    The identifier of the protected resource.
    """
    authorization_servers: Optional[List[str]] = None
    """
    List of authorization servers whose tokens are accepted by this resource.
    """


class HarnessAgentCoreBrowserConfig(BaseModel):
    browserArn: Optional[str] = Field(
        default=None,
        pattern='^arn:aws(-[^:]+)?:bedrock-agentcore:[a-z0-9-]+:(aws|[0-9]{12}):browser(-custom)?/(aws\\.browser\\.v1|[a-zA-Z][a-zA-Z0-9_]{0,47}-[a-zA-Z0-9]{10})$',
    )


class HarnessAgentCoreCodeInterpreterConfig(BaseModel):
    codeInterpreterArn: Optional[str] = Field(
        default=None,
        pattern='^arn:aws(-[^:]+)?:bedrock-agentcore:[a-z0-9-]+:(aws|[0-9]{12}):code-interpreter(-custom)?/(aws\\.codeinterpreter\\.v1|[a-zA-Z][a-zA-Z0-9_]{0,47}-[a-zA-Z0-9]{10})$',
    )


class HarnessBedrockModelConfig(BaseModel):
    modelId: str
    maxTokens: Optional[int] = Field(default=None, ge=1)
    temperature: Optional[float] = Field(default=None, ge=0.0, le=2.0)
    topP: Optional[float] = Field(default=None, ge=0.0, le=1.0)


class HarnessContentBlock1(BaseModel):
    text: SecretStr = Field(..., min_length=1)


class HarnessContentBlockDelta1(BaseModel):
    text: SecretStr = Field(..., min_length=1)


class HarnessContentBlockStopEvent(BaseModel):
    contentBlockIndex: int


class HarnessConversationRole(str, Enum):
    user = 'user'
    assistant = 'assistant'


class HarnessGeminiModelConfig(BaseModel):
    modelId: str
    apiKeyArn: str = Field(
        ...,
        pattern='^arn:aws:bedrock-agentcore:[a-z0-9-]+:[0-9]{12}:token-vault/[a-zA-Z0-9-.]+/apikeycredentialprovider/[a-zA-Z0-9-.]+$',
    )
    maxTokens: Optional[int] = Field(default=None, ge=1)
    temperature: Optional[float] = Field(default=None, ge=0.0, le=2.0)
    topP: Optional[float] = Field(default=None, ge=0.0, le=1.0)
    topK: Optional[int] = Field(default=None, ge=0, le=500)


class HarnessInlineFunctionConfig(BaseModel):
    description: SecretStr = Field(..., max_length=4096, min_length=1)
    inputSchema: Any


class HarnessMessageStartEvent(BaseModel):
    role: HarnessConversationRole


class HarnessModelConfiguration1(BaseModel):
    bedrockModelConfig: HarnessBedrockModelConfig


class HarnessModelConfiguration3(BaseModel):
    geminiModelConfig: HarnessGeminiModelConfig


class HarnessOpenAiModelConfig(BaseModel):
    modelId: str
    apiKeyArn: str = Field(
        ...,
        pattern='^arn:aws:bedrock-agentcore:[a-z0-9-]+:[0-9]{12}:token-vault/[a-zA-Z0-9-.]+/apikeycredentialprovider/[a-zA-Z0-9-.]+$',
    )
    maxTokens: Optional[int] = Field(default=None, ge=1)
    temperature: Optional[float] = Field(default=None, ge=0.0, le=2.0)
    topP: Optional[float] = Field(default=None, ge=0.0, le=1.0)


class HarnessReasoningContentBlock2(BaseModel):
    redactedContent: str


class HarnessReasoningContentBlockDelta1(BaseModel):
    text: str


class HarnessReasoningContentBlockDelta2(BaseModel):
    redactedContent: str = Field(..., max_length=100000000)


class HarnessReasoningContentBlockDelta3(BaseModel):
    signature: str


class HarnessReasoningContentBlockDelta(
    RootModel[
        Union[
            HarnessReasoningContentBlockDelta1,
            HarnessReasoningContentBlockDelta2,
            HarnessReasoningContentBlockDelta3,
        ]
    ]
):
    root: Union[
        HarnessReasoningContentBlockDelta1,
        HarnessReasoningContentBlockDelta2,
        HarnessReasoningContentBlockDelta3,
    ]


class HarnessReasoningTextBlock(BaseModel):
    text: str
    signature: Optional[str] = None


class HarnessSkill1(BaseModel):
    path: str = Field(..., min_length=1)


class HarnessSkill(RootModel[HarnessSkill1]):
    root: HarnessSkill1


class HarnessStopReason(str, Enum):
    end_turn = 'end_turn'
    tool_use = 'tool_use'
    tool_result = 'tool_result'
    max_tokens = 'max_tokens'
    stop_sequence = 'stop_sequence'
    content_filtered = 'content_filtered'
    malformed_model_output = 'malformed_model_output'
    malformed_tool_use = 'malformed_tool_use'
    interrupted = 'interrupted'
    partial_turn = 'partial_turn'
    model_context_window_exceeded = 'model_context_window_exceeded'
    max_iterations_exceeded = 'max_iterations_exceeded'
    max_output_tokens_exceeded = 'max_output_tokens_exceeded'
    timeout_exceeded = 'timeout_exceeded'


class HarnessStreamMetrics(BaseModel):
    latencyMs: int


class HarnessSystemContentBlock1(BaseModel):
    text: SecretStr = Field(..., min_length=1)


class HarnessSystemContentBlock(RootModel[HarnessSystemContentBlock1]):
    root: HarnessSystemContentBlock1


class HarnessTokenUsage(BaseModel):
    inputTokens: int = Field(..., ge=0)
    outputTokens: int = Field(..., ge=0)
    totalTokens: int = Field(..., ge=0)
    cacheReadInputTokens: Optional[int] = Field(default=None, ge=0)
    cacheWriteInputTokens: Optional[int] = Field(default=None, ge=0)


class HarnessToolConfiguration2(BaseModel):
    agentCoreBrowser: HarnessAgentCoreBrowserConfig


class HarnessToolConfiguration4(BaseModel):
    inlineFunction: HarnessInlineFunctionConfig


class HarnessToolConfiguration5(BaseModel):
    agentCoreCodeInterpreter: HarnessAgentCoreCodeInterpreterConfig


class HarnessToolResultBlockDelta1(BaseModel):
    text: SecretStr = Field(..., min_length=1)


class HarnessToolResultBlockDelta2(BaseModel):
    json_: Any = Field(..., alias='json')


class HarnessToolResultBlockDelta(
    RootModel[Union[HarnessToolResultBlockDelta1, HarnessToolResultBlockDelta2]]
):
    root: Union[HarnessToolResultBlockDelta1, HarnessToolResultBlockDelta2]


class HarnessToolResultContentBlock1(BaseModel):
    text: SecretStr = Field(..., min_length=1)


class HarnessToolResultContentBlock2(BaseModel):
    json_: Any = Field(..., alias='json')


class HarnessToolResultContentBlock(
    RootModel[Union[HarnessToolResultContentBlock1, HarnessToolResultContentBlock2]]
):
    root: Union[HarnessToolResultContentBlock1, HarnessToolResultContentBlock2]


class HarnessToolType(str, Enum):
    remote_mcp = 'remote_mcp'
    agentcore_browser = 'agentcore_browser'
    agentcore_gateway = 'agentcore_gateway'
    inline_function = 'inline_function'
    agentcore_code_interpreter = 'agentcore_code_interpreter'


class HarnessToolUseBlockDelta(BaseModel):
    input: SecretStr = Field(..., min_length=1)


class HarnessToolUseStatus(str, Enum):
    success = 'success'
    error = 'error'


class HarnessToolUseType(str, Enum):
    tool_use = 'tool_use'
    server_tool_use = 'server_tool_use'
    mcp_tool_use = 'mcp_tool_use'


class HttpHeadersMap(RootModel[Optional[Dict[str, str]]]):
    root: Optional[Dict[str, str]] = Field(default=None, max_length=16383, min_length=1)
    """
    The value of an HTTP header.
    """


class InputContentBlock(BaseModel):
    path: str = Field(..., max_length=100000000)
    text: Optional[str] = Field(default=None, max_length=100000000)
    blob: Optional[str] = Field(default=None, max_length=100000000)


class InternalServerException(BaseModel):
    message: Optional[str] = Field(default=None, pattern='^[\\s\\S]+$')


class InternalServerExceptionResponseContent(BaseModel):
    message: Optional[str] = Field(default=None, pattern='^[\\s\\S]+$')


class InvokeAgentRuntimeCommandRequestBody(BaseModel):
    command: str = Field(..., max_length=65536, min_length=1)
    """
    The command to execute in the runtime container
    """
    timeout: Optional[int] = None
    """
    Command timeout in seconds (default: 300, min:1, max: 3600)
    """


class InvokeAgentRuntimeCommandStreamOutput2(BaseModel):
    accessDeniedException: AccessDeniedException


class InvokeAgentRuntimeCommandStreamOutput3(BaseModel):
    internalServerException: InternalServerException


class InvokeAgentRuntimeInputPayload(RootModel[str]):
    root: str = Field(..., max_length=100000000)


class InvokeAgentRuntimeOutputPayload(RootModel[str]):
    root: str


class AllowedTool(RootModel[str]):
    root: str = Field(
        ..., max_length=64, min_length=1, pattern='^(\\*|@?[^/]+(/[^/]+)?)$'
    )


class InvokeHarnessStreamOutput1(BaseModel):
    messageStart: HarnessMessageStartEvent


class InvokeHarnessStreamOutput4(BaseModel):
    contentBlockStop: HarnessContentBlockStopEvent


class InvokeHarnessStreamOutput7(BaseModel):
    internalServerException: InternalServerException


class KeyPressArguments(BaseModel):
    key: str
    presses: Optional[int] = Field(default=None, ge=1, le=100)


class KeyPressResult(BaseModel):
    status: BrowserActionStatus
    error: Optional[str] = None


class KeyShortcutArguments(BaseModel):
    keys: List[str] = Field(..., max_length=5, min_length=1)


class KeyShortcutResult(BaseModel):
    status: BrowserActionStatus
    error: Optional[str] = None


class KeyTypeArguments(BaseModel):
    text: str = Field(..., max_length=10000)


class KeyTypeResult(BaseModel):
    status: BrowserActionStatus
    error: Optional[str] = None


class LanguageRuntime(str, Enum):
    nodejs = 'nodejs'
    deno = 'deno'
    python = 'python'


class ListBrowserSessionsRequestContent(BaseModel):
    maxResults: Optional[int] = Field(default=None, ge=1, le=100)
    nextToken: Optional[str] = Field(
        default=None, max_length=2048, min_length=1, pattern='^\\S*$'
    )
    status: Optional[BrowserSessionStatus] = None


class ListBrowserSessionsResponseContent(BaseModel):
    items: List[BrowserSessionSummary]
    nextToken: Optional[str] = Field(
        default=None, max_length=2048, min_length=1, pattern='^\\S*$'
    )


class ListCodeInterpreterSessionsRequestContent(BaseModel):
    maxResults: Optional[int] = Field(default=None, ge=1, le=100)
    nextToken: Optional[str] = Field(
        default=None, max_length=2048, min_length=1, pattern='^\\S*$'
    )
    status: Optional[CodeInterpreterSessionStatus] = None


class ListCodeInterpreterSessionsResponseContent(BaseModel):
    items: List[CodeInterpreterSessionSummary]
    nextToken: Optional[str] = Field(
        default=None, max_length=2048, min_length=1, pattern='^\\S*$'
    )


class LiveViewStream(BaseModel):
    streamEndpoint: Optional[str] = Field(default=None, max_length=512, min_length=10)


class MouseButton(str, Enum):
    LEFT = 'LEFT'
    RIGHT = 'RIGHT'
    MIDDLE = 'MIDDLE'


class MouseClickArguments(BaseModel):
    x: int
    y: int
    button: Optional[MouseButton] = None
    clickCount: Optional[int] = Field(default=None, ge=1, le=10)


class MouseClickResult(BaseModel):
    status: BrowserActionStatus
    error: Optional[str] = None


class MouseDragArguments(BaseModel):
    endX: int
    endY: int
    startX: int
    startY: int
    button: Optional[MouseButton] = None


class MouseDragResult(BaseModel):
    status: BrowserActionStatus
    error: Optional[str] = None


class MouseMoveArguments(BaseModel):
    x: int
    y: int


class MouseMoveResult(BaseModel):
    status: BrowserActionStatus
    error: Optional[str] = None


class MouseScrollArguments(BaseModel):
    x: int
    y: int
    deltaX: Optional[int] = Field(default=None, ge=-1000, le=1000)
    deltaY: Optional[int] = Field(default=None, ge=-1000, le=1000)


class MouseScrollResult(BaseModel):
    status: BrowserActionStatus
    error: Optional[str] = None


class Scope(RootModel[str]):
    root: str = Field(..., max_length=64, min_length=1)


class OAuthCustomParameters(RootModel[Optional[Dict[str, SecretStr]]]):
    root: Optional[Dict[str, SecretStr]] = Field(
        default=None, max_length=2048, min_length=1
    )


class OAuthGrantType(str, Enum):
    CLIENT_CREDENTIALS = 'CLIENT_CREDENTIALS'
    AUTHORIZATION_CODE = 'AUTHORIZATION_CODE'
    TOKEN_EXCHANGE = 'TOKEN_EXCHANGE'


class ProgrammingLanguage(str, Enum):
    python = 'python'
    javascript = 'javascript'
    typescript = 'typescript'


class ProxyBypass(BaseModel):
    domainPatterns: Optional[List[DomainPattern]] = Field(
        default=None, max_length=100, min_length=1
    )


class ProxyCredentials1(BaseModel):
    basicAuth: BasicAuth


class ProxyCredentials(RootModel[ProxyCredentials1]):
    root: ProxyCredentials1


class ResourceContentType(str, Enum):
    text = 'text'
    blob = 'blob'


class ResourceNotFoundException(BaseModel):
    message: Optional[str] = Field(default=None, pattern='^[\\s\\S]+$')


class ResourceNotFoundExceptionResponseContent(BaseModel):
    message: Optional[str] = Field(default=None, pattern='^[\\s\\S]+$')


class ResponseChunk(BaseModel):
    contentStart: Optional[ContentStartEvent] = None
    contentDelta: Optional[ContentDeltaEvent] = None
    contentStop: Optional[ContentStopEvent] = None


class RuntimeClientError(BaseModel):
    message: Optional[str] = Field(default=None, pattern='^[\\s\\S]+$')


class RuntimeClientErrorResponseContent(BaseModel):
    message: Optional[str] = Field(default=None, pattern='^[\\s\\S]+$')


class S3Location(BaseModel):
    bucket: str = Field(
        ..., max_length=63, min_length=3, pattern='^[a-z0-9][a-z0-9.-]*[a-z0-9]$'
    )
    prefix: str = Field(..., max_length=1024, min_length=1)
    versionId: Optional[str] = Field(default=None, max_length=1024, min_length=1)


class SaveBrowserSessionProfileRequestContent(BaseModel):
    browserIdentifier: str
    sessionId: str = Field(..., pattern='^[0-9a-zA-Z]{1,40}$')
    clientToken: Optional[str] = Field(
        default=None,
        max_length=256,
        min_length=33,
        pattern='^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,256}$',
    )


class SaveBrowserSessionProfileResponseContent(BaseModel):
    profileIdentifier: str = Field(
        ..., pattern='^[a-zA-Z][a-zA-Z0-9_]{0,47}-[a-zA-Z0-9]{10}$'
    )
    browserIdentifier: str
    sessionId: str = Field(..., pattern='^[0-9a-zA-Z]{1,40}$')


class ScreenshotFormat(str, Enum):
    PNG = 'PNG'


class ScreenshotResult(BaseModel):
    status: BrowserActionStatus
    error: Optional[str] = None
    data: Optional[str] = None


class SecretsManagerLocation(BaseModel):
    secretArn: str = Field(
        ...,
        pattern='^arn:aws(-[a-z-]+)?:secretsmanager:[a-z0-9-]+:[0-9]{12}:secret:[a-zA-Z0-9/_+=.@-]+$',
    )


class ServiceQuotaExceededException(BaseModel):
    message: Optional[str] = Field(default=None, pattern='^[\\s\\S]+$')


class ServiceQuotaExceededExceptionResponseContent(BaseModel):
    message: Optional[str] = Field(default=None, pattern='^[\\s\\S]+$')


class SignBrowserPayloadInputPayload(RootModel[str]):
    root: str


class SignBrowserPayloadOutputPayload(RootModel[str]):
    root: str


class StartCodeInterpreterSessionResponseContent(BaseModel):
    codeInterpreterIdentifier: str
    sessionId: str = Field(..., pattern='^[0-9a-zA-Z]{1,40}$')
    createdAt: datetime


class StopBrowserSessionRequestContent(BaseModel):
    clientToken: Optional[str] = Field(
        default=None,
        max_length=256,
        min_length=33,
        pattern='^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,256}$',
    )


class StopBrowserSessionResponseContent(BaseModel):
    browserIdentifier: str
    sessionId: str = Field(..., pattern='^[0-9a-zA-Z]{1,40}$')
    lastUpdatedAt: datetime


class StopCodeInterpreterSessionRequestContent(BaseModel):
    clientToken: Optional[str] = Field(
        default=None,
        max_length=256,
        min_length=33,
        pattern='^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,256}$',
    )


class StopCodeInterpreterSessionResponseContent(BaseModel):
    codeInterpreterIdentifier: str
    sessionId: str = Field(..., pattern='^[0-9a-zA-Z]{1,40}$')
    lastUpdatedAt: datetime


class StopRuntimeSessionRequestContent(BaseModel):
    clientToken: Optional[str] = Field(
        default=None,
        max_length=256,
        min_length=33,
        pattern='^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,256}$',
    )


class StreamUpdate1(BaseModel):
    automationStreamUpdate: AutomationStreamUpdate


class StreamUpdate(RootModel[StreamUpdate1]):
    root: StreamUpdate1


class TaskStatus(str, Enum):
    submitted = 'submitted'
    working = 'working'
    completed = 'completed'
    canceled = 'canceled'
    failed = 'failed'


class ThrottlingException(BaseModel):
    message: Optional[str] = Field(default=None, pattern='^[\\s\\S]+$')


class ThrottlingExceptionResponseContent(BaseModel):
    message: Optional[str] = Field(default=None, pattern='^[\\s\\S]+$')


class Path(RootModel[str]):
    root: str = Field(..., max_length=100000000)


class ToolArguments(BaseModel):
    code: Optional[str] = Field(default=None, max_length=100000000)
    language: Optional[ProgrammingLanguage] = None
    clearContext: Optional[bool] = None
    command: Optional[str] = Field(default=None, max_length=100000000)
    path: Optional[str] = Field(default=None, max_length=100000000)
    paths: Optional[List[Path]] = None
    content: Optional[List[InputContentBlock]] = None
    directoryPath: Optional[str] = Field(default=None, max_length=100000000)
    taskId: Optional[str] = Field(default=None, max_length=100000000)
    runtime: Optional[LanguageRuntime] = None


class ToolName(str, Enum):
    executeCode = 'executeCode'
    executeCommand = 'executeCommand'
    readFiles = 'readFiles'
    listFiles = 'listFiles'
    removeFiles = 'removeFiles'
    writeFiles = 'writeFiles'
    startCommandExecution = 'startCommandExecution'
    getTask = 'getTask'
    stopTask = 'stopTask'


class ToolResultStructuredContent(BaseModel):
    taskId: Optional[str] = None
    taskStatus: Optional[TaskStatus] = None
    stdout: Optional[str] = None
    stderr: Optional[str] = None
    exitCode: Optional[int] = None
    executionTime: Optional[float] = None


class UnauthorizedExceptionResponseContent(BaseModel):
    message: Optional[str] = Field(default=None, pattern='^[\\s\\S]+$')


class Unit(BaseModel):
    pass


class UpdateBrowserStreamRequestContent(BaseModel):
    streamUpdate: StreamUpdate
    clientToken: Optional[str] = Field(
        default=None,
        max_length=256,
        min_length=33,
        pattern='^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,256}$',
    )


class ValidationExceptionField(BaseModel):
    name: str
    message: str


class ValidationExceptionReason(str, Enum):
    CannotParse = 'CannotParse'
    FieldValidationFailed = 'FieldValidationFailed'
    IdempotentParameterMismatchException = 'IdempotentParameterMismatchException'
    EventInOtherSession = 'EventInOtherSession'
    ResourceConflict = 'ResourceConflict'


class ValidationExceptionResponseContent(BaseModel):
    message: str
    reason: ValidationExceptionReason
    fieldList: Optional[List[ValidationExceptionField]] = None


class ViewPort(BaseModel):
    width: int = Field(..., ge=320, le=3840)
    height: int = Field(..., ge=240, le=2160)


class AutomationStream(BaseModel):
    streamEndpoint: str = Field(..., max_length=512, min_length=10)
    streamStatus: AutomationStreamStatus


class BrowserAction1(BaseModel):
    mouseClick: MouseClickArguments


class BrowserAction2(BaseModel):
    mouseMove: MouseMoveArguments


class BrowserAction3(BaseModel):
    mouseDrag: MouseDragArguments


class BrowserAction4(BaseModel):
    mouseScroll: MouseScrollArguments


class BrowserAction5(BaseModel):
    keyType: KeyTypeArguments


class BrowserAction6(BaseModel):
    keyPress: KeyPressArguments


class BrowserAction7(BaseModel):
    keyShortcut: KeyShortcutArguments


class BrowserActionResult1(BaseModel):
    mouseClick: MouseClickResult


class BrowserActionResult2(BaseModel):
    mouseMove: MouseMoveResult


class BrowserActionResult3(BaseModel):
    mouseDrag: MouseDragResult


class BrowserActionResult4(BaseModel):
    mouseScroll: MouseScrollResult


class BrowserActionResult5(BaseModel):
    keyType: KeyTypeResult


class BrowserActionResult6(BaseModel):
    keyPress: KeyPressResult


class BrowserActionResult7(BaseModel):
    keyShortcut: KeyShortcutResult


class BrowserActionResult8(BaseModel):
    screenshot: ScreenshotResult


class BrowserActionResult(
    RootModel[
        Union[
            BrowserActionResult1,
            BrowserActionResult2,
            BrowserActionResult3,
            BrowserActionResult4,
            BrowserActionResult5,
            BrowserActionResult6,
            BrowserActionResult7,
            BrowserActionResult8,
        ]
    ]
):
    root: Union[
        BrowserActionResult1,
        BrowserActionResult2,
        BrowserActionResult3,
        BrowserActionResult4,
        BrowserActionResult5,
        BrowserActionResult6,
        BrowserActionResult7,
        BrowserActionResult8,
    ]


class BrowserSessionStream(BaseModel):
    automationStream: AutomationStream
    liveViewStream: Optional[LiveViewStream] = None


class CertificateLocation1(BaseModel):
    secretsManager: SecretsManagerLocation


class CertificateLocation(RootModel[CertificateLocation1]):
    root: CertificateLocation1


class CodeInterpreterStreamOutput3(BaseModel):
    conflictException: ConflictException


class CodeInterpreterStreamOutput4(BaseModel):
    internalServerException: InternalServerException


class CodeInterpreterStreamOutput5(BaseModel):
    resourceNotFoundException: ResourceNotFoundException


class CodeInterpreterStreamOutput6(BaseModel):
    serviceQuotaExceededException: ServiceQuotaExceededException


class CodeInterpreterStreamOutput7(BaseModel):
    throttlingException: ThrottlingException


class ExternalProxy(BaseModel):
    server: str = Field(
        ...,
        max_length=253,
        min_length=1,
        pattern='^[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?(\\.[a-zA-Z0-9]([a-zA-Z0-9\\-]{0,61}[a-zA-Z0-9])?)*$',
    )
    port: int = Field(..., ge=1, le=65535)
    domainPatterns: Optional[List[DomainPattern]] = Field(
        default=None, max_length=100, min_length=1
    )
    credentials: Optional[ProxyCredentials] = None


class HarnessContentBlockDelta2(BaseModel):
    toolUse: HarnessToolUseBlockDelta


class HarnessContentBlockDelta3(BaseModel):
    toolResult: List[HarnessToolResultBlockDelta]


class HarnessContentBlockDelta4(BaseModel):
    reasoningContent: HarnessReasoningContentBlockDelta


class HarnessContentBlockDelta(
    RootModel[
        Union[
            HarnessContentBlockDelta1,
            HarnessContentBlockDelta2,
            HarnessContentBlockDelta3,
            HarnessContentBlockDelta4,
        ]
    ]
):
    root: Union[
        HarnessContentBlockDelta1,
        HarnessContentBlockDelta2,
        HarnessContentBlockDelta3,
        HarnessContentBlockDelta4,
    ]


class HarnessContentBlockDeltaEvent(BaseModel):
    contentBlockIndex: int
    delta: HarnessContentBlockDelta


class HarnessGatewayOutboundAuth1(BaseModel):
    awsIam: Unit


class HarnessGatewayOutboundAuth2(BaseModel):
    none: Unit


class HarnessMessageStopEvent(BaseModel):
    stopReason: HarnessStopReason


class HarnessMetadataEvent(BaseModel):
    usage: HarnessTokenUsage
    metrics: HarnessStreamMetrics


class HarnessModelConfiguration2(BaseModel):
    openAiModelConfig: HarnessOpenAiModelConfig


class HarnessModelConfiguration(
    RootModel[
        Union[
            HarnessModelConfiguration1,
            HarnessModelConfiguration2,
            HarnessModelConfiguration3,
        ]
    ]
):
    root: Union[
        HarnessModelConfiguration1,
        HarnessModelConfiguration2,
        HarnessModelConfiguration3,
    ]


class HarnessReasoningContentBlock1(BaseModel):
    reasoningText: HarnessReasoningTextBlock


class HarnessReasoningContentBlock(
    RootModel[Union[HarnessReasoningContentBlock1, HarnessReasoningContentBlock2]]
):
    root: Union[HarnessReasoningContentBlock1, HarnessReasoningContentBlock2]


class HarnessRemoteMcpConfig(BaseModel):
    url: SecretStr = Field(..., max_length=16383, min_length=1)
    headers: Optional[HttpHeadersMap] = None


class HarnessToolConfiguration1(BaseModel):
    remoteMcp: HarnessRemoteMcpConfig


class HarnessToolResultBlock(BaseModel):
    toolUseId: str = Field(..., max_length=64, min_length=1, pattern='^[a-zA-Z0-9_-]+$')
    content: List[HarnessToolResultContentBlock]
    status: Optional[HarnessToolUseStatus] = None
    type: Optional[HarnessToolUseType] = None


class HarnessToolResultBlockStart(BaseModel):
    toolUseId: str = Field(..., max_length=64, min_length=1, pattern='^[a-zA-Z0-9_-]+$')
    status: Optional[HarnessToolUseStatus] = None


class HarnessToolUseBlock(BaseModel):
    name: str = Field(..., max_length=64, min_length=1, pattern='^[a-zA-Z0-9_-]+$')
    toolUseId: str = Field(..., max_length=64, min_length=1, pattern='^[a-zA-Z0-9_-]+$')
    input: Any
    type: Optional[HarnessToolUseType] = None
    serverName: Optional[str] = None


class HarnessToolUseBlockStart(BaseModel):
    toolUseId: str = Field(..., max_length=64, min_length=1, pattern='^[a-zA-Z0-9_-]+$')
    name: str = Field(..., max_length=64, min_length=1, pattern='^[a-zA-Z0-9_-]+$')
    type: Optional[HarnessToolUseType] = None
    serverName: Optional[str] = None


class InvokeAgentRuntimeCommandStreamOutput1(BaseModel):
    chunk: ResponseChunk


class InvokeAgentRuntimeCommandStreamOutput4(BaseModel):
    resourceNotFoundException: ResourceNotFoundException


class InvokeAgentRuntimeCommandStreamOutput5(BaseModel):
    serviceQuotaExceededException: ServiceQuotaExceededException


class InvokeAgentRuntimeCommandStreamOutput6(BaseModel):
    throttlingException: ThrottlingException


class InvokeAgentRuntimeCommandStreamOutput8(BaseModel):
    runtimeClientError: RuntimeClientError


class InvokeBrowserResponseContent(BaseModel):
    result: BrowserActionResult


class InvokeCodeInterpreterRequestContent(BaseModel):
    name: ToolName
    arguments: ToolArguments


class InvokeHarnessStreamOutput3(BaseModel):
    contentBlockDelta: HarnessContentBlockDeltaEvent


class InvokeHarnessStreamOutput5(BaseModel):
    messageStop: HarnessMessageStopEvent


class InvokeHarnessStreamOutput6(BaseModel):
    metadata: HarnessMetadataEvent


class InvokeHarnessStreamOutput9(BaseModel):
    runtimeClientError: RuntimeClientError


class OAuthCredentialProvider(BaseModel):
    providerArn: str = Field(
        ..., pattern='^arn:([^:]*):([^:]*):([^:]*):([0-9]{12})?:(.+)$'
    )
    scopes: List[Scope] = Field(..., max_length=100)
    customParameters: Optional[OAuthCustomParameters] = None
    grantType: Optional[OAuthGrantType] = None
    defaultReturnUrl: Optional[str] = Field(
        default=None, max_length=2048, min_length=1, pattern='^\\w+:(\\/?\\/?)[^\\s]+$'
    )
    enableScopeDiscovery: Optional[bool] = None


class Proxy1(BaseModel):
    externalProxy: ExternalProxy


class Proxy(RootModel[Proxy1]):
    root: Proxy1


class ProxyConfiguration(BaseModel):
    proxies: List[Proxy] = Field(..., max_length=5, min_length=1)
    bypass: Optional[ProxyBypass] = None


class ResourceContent(BaseModel):
    type: ResourceContentType
    uri: Optional[str] = None
    mimeType: Optional[str] = None
    text: Optional[str] = None
    blob: Optional[str] = None


class ResourceLocation1(BaseModel):
    s3: S3Location


class ResourceLocation(RootModel[ResourceLocation1]):
    root: ResourceLocation1


class ScreenshotArguments(BaseModel):
    format: Optional[ScreenshotFormat] = None


class StartBrowserSessionResponseContent(BaseModel):
    browserIdentifier: str
    sessionId: str = Field(..., pattern='^[0-9a-zA-Z]{1,40}$')
    createdAt: datetime
    streams: Optional[BrowserSessionStream] = None


class UpdateBrowserStreamResponseContent(BaseModel):
    browserIdentifier: str
    sessionId: str = Field(..., pattern='^[0-9a-zA-Z]{1,40}$')
    streams: BrowserSessionStream
    updatedAt: datetime


class ValidationException(BaseModel):
    message: str
    reason: ValidationExceptionReason
    fieldList: Optional[List[ValidationExceptionField]] = None


class BrowserAction8(BaseModel):
    screenshot: ScreenshotArguments


class BrowserAction(
    RootModel[
        Union[
            BrowserAction1,
            BrowserAction2,
            BrowserAction3,
            BrowserAction4,
            BrowserAction5,
            BrowserAction6,
            BrowserAction7,
            BrowserAction8,
        ]
    ]
):
    root: Union[
        BrowserAction1,
        BrowserAction2,
        BrowserAction3,
        BrowserAction4,
        BrowserAction5,
        BrowserAction6,
        BrowserAction7,
        BrowserAction8,
    ]


class BrowserEnterprisePolicy(BaseModel):
    location: ResourceLocation
    type: Optional[BrowserEnterprisePolicyType] = None


class BrowserExtension(BaseModel):
    location: ResourceLocation


class Certificate(BaseModel):
    location: CertificateLocation


class CodeInterpreterStreamOutput8(BaseModel):
    validationException: ValidationException


class ContentBlock(BaseModel):
    type: ContentBlockType
    text: Optional[str] = None
    data: Optional[str] = None
    mimeType: Optional[str] = None
    uri: Optional[str] = None
    name: Optional[str] = None
    description: Optional[str] = None
    size: Optional[int] = None
    resource: Optional[ResourceContent] = None


class GetBrowserSessionResponseContent(BaseModel):
    browserIdentifier: str
    sessionId: str = Field(..., pattern='^[0-9a-zA-Z]{1,40}$')
    name: Optional[str] = Field(default=None, max_length=100, min_length=1)
    createdAt: datetime
    viewPort: Optional[ViewPort] = None
    extensions: Optional[List[BrowserExtension]] = Field(
        default=None, max_length=10, min_length=1
    )
    enterprisePolicies: Optional[List[BrowserEnterprisePolicy]] = Field(
        default=None, max_length=100, min_length=0
    )
    profileConfiguration: Optional[BrowserProfileConfiguration] = None
    sessionTimeoutSeconds: Optional[int] = Field(default=None, ge=1, le=28800)
    status: Optional[BrowserSessionStatus] = None
    streams: Optional[BrowserSessionStream] = None
    proxyConfiguration: Optional[ProxyConfiguration] = None
    certificates: Optional[List[Certificate]] = Field(
        default=None, max_length=200, min_length=1
    )
    sessionReplayArtifact: Optional[str] = None
    lastUpdatedAt: Optional[datetime] = None


class GetCodeInterpreterSessionResponseContent(BaseModel):
    codeInterpreterIdentifier: str
    sessionId: str = Field(..., pattern='^[0-9a-zA-Z]{1,40}$')
    name: Optional[str] = Field(default=None, max_length=100, min_length=1)
    createdAt: datetime
    sessionTimeoutSeconds: Optional[int] = Field(default=None, ge=1, le=28800)
    status: Optional[CodeInterpreterSessionStatus] = None
    certificates: Optional[List[Certificate]] = Field(
        default=None, max_length=200, min_length=1
    )


class HarnessContentBlock2(BaseModel):
    toolUse: HarnessToolUseBlock


class HarnessContentBlock3(BaseModel):
    toolResult: HarnessToolResultBlock


class HarnessContentBlock4(BaseModel):
    reasoningContent: HarnessReasoningContentBlock


class HarnessContentBlock(
    RootModel[
        Union[
            HarnessContentBlock1,
            HarnessContentBlock2,
            HarnessContentBlock3,
            HarnessContentBlock4,
        ]
    ]
):
    root: Union[
        HarnessContentBlock1,
        HarnessContentBlock2,
        HarnessContentBlock3,
        HarnessContentBlock4,
    ]


class HarnessContentBlockStart1(BaseModel):
    toolUse: HarnessToolUseBlockStart


class HarnessContentBlockStart2(BaseModel):
    toolResult: HarnessToolResultBlockStart


class HarnessContentBlockStart(
    RootModel[Union[HarnessContentBlockStart1, HarnessContentBlockStart2]]
):
    root: Union[HarnessContentBlockStart1, HarnessContentBlockStart2]


class HarnessContentBlockStartEvent(BaseModel):
    contentBlockIndex: int
    start: HarnessContentBlockStart


class HarnessGatewayOutboundAuth3(BaseModel):
    oauth: OAuthCredentialProvider


class HarnessGatewayOutboundAuth(
    RootModel[
        Union[
            HarnessGatewayOutboundAuth1,
            HarnessGatewayOutboundAuth2,
            HarnessGatewayOutboundAuth3,
        ]
    ]
):
    root: Union[
        HarnessGatewayOutboundAuth1,
        HarnessGatewayOutboundAuth2,
        HarnessGatewayOutboundAuth3,
    ]


class HarnessMessage(BaseModel):
    role: HarnessConversationRole
    content: List[HarnessContentBlock]


class InvokeAgentRuntimeCommandStreamOutput7(BaseModel):
    validationException: ValidationException


class InvokeAgentRuntimeCommandStreamOutput(
    RootModel[
        Union[
            InvokeAgentRuntimeCommandStreamOutput1,
            InvokeAgentRuntimeCommandStreamOutput2,
            InvokeAgentRuntimeCommandStreamOutput3,
            InvokeAgentRuntimeCommandStreamOutput4,
            InvokeAgentRuntimeCommandStreamOutput5,
            InvokeAgentRuntimeCommandStreamOutput6,
            InvokeAgentRuntimeCommandStreamOutput7,
            InvokeAgentRuntimeCommandStreamOutput8,
        ]
    ]
):
    root: Union[
        InvokeAgentRuntimeCommandStreamOutput1,
        InvokeAgentRuntimeCommandStreamOutput2,
        InvokeAgentRuntimeCommandStreamOutput3,
        InvokeAgentRuntimeCommandStreamOutput4,
        InvokeAgentRuntimeCommandStreamOutput5,
        InvokeAgentRuntimeCommandStreamOutput6,
        InvokeAgentRuntimeCommandStreamOutput7,
        InvokeAgentRuntimeCommandStreamOutput8,
    ]
    """
    Streaming output for InvokeAgentRuntimeCommand operation
    Delivers typed events: contentStart (first), contentDelta (middle), contentStop (last)
    """


class InvokeBrowserRequestContent(BaseModel):
    action: BrowserAction


class InvokeHarnessStreamOutput2(BaseModel):
    contentBlockStart: HarnessContentBlockStartEvent


class InvokeHarnessStreamOutput8(BaseModel):
    validationException: ValidationException


class InvokeHarnessStreamOutput(
    RootModel[
        Union[
            InvokeHarnessStreamOutput1,
            InvokeHarnessStreamOutput2,
            InvokeHarnessStreamOutput3,
            InvokeHarnessStreamOutput4,
            InvokeHarnessStreamOutput5,
            InvokeHarnessStreamOutput6,
            InvokeHarnessStreamOutput7,
            InvokeHarnessStreamOutput8,
            InvokeHarnessStreamOutput9,
        ]
    ]
):
    root: Union[
        InvokeHarnessStreamOutput1,
        InvokeHarnessStreamOutput2,
        InvokeHarnessStreamOutput3,
        InvokeHarnessStreamOutput4,
        InvokeHarnessStreamOutput5,
        InvokeHarnessStreamOutput6,
        InvokeHarnessStreamOutput7,
        InvokeHarnessStreamOutput8,
        InvokeHarnessStreamOutput9,
    ]


class StartBrowserSessionRequestContent(BaseModel):
    name: Optional[str] = Field(default=None, max_length=100, min_length=1)
    sessionTimeoutSeconds: Optional[int] = Field(default=None, ge=1, le=28800)
    viewPort: Optional[ViewPort] = None
    extensions: Optional[List[BrowserExtension]] = Field(
        default=None, max_length=10, min_length=1
    )
    profileConfiguration: Optional[BrowserProfileConfiguration] = None
    proxyConfiguration: Optional[ProxyConfiguration] = None
    enterprisePolicies: Optional[List[BrowserEnterprisePolicy]] = Field(
        default=None, max_length=100, min_length=0
    )
    certificates: Optional[List[Certificate]] = Field(
        default=None, max_length=200, min_length=1
    )
    clientToken: Optional[str] = Field(
        default=None,
        max_length=256,
        min_length=33,
        pattern='^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,256}$',
    )


class StartCodeInterpreterSessionRequestContent(BaseModel):
    name: Optional[str] = Field(default=None, max_length=100, min_length=1)
    sessionTimeoutSeconds: Optional[int] = Field(default=None, ge=1, le=28800)
    certificates: Optional[List[Certificate]] = Field(
        default=None, max_length=200, min_length=1
    )
    clientToken: Optional[str] = Field(
        default=None,
        max_length=256,
        min_length=33,
        pattern='^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,256}$',
    )


class CodeInterpreterResult(BaseModel):
    content: List[ContentBlock]
    structuredContent: Optional[ToolResultStructuredContent] = None
    isError: Optional[bool] = None


class CodeInterpreterStreamOutput1(BaseModel):
    result: CodeInterpreterResult


class CodeInterpreterStreamOutput(
    RootModel[
        Union[
            CodeInterpreterStreamOutput1,
            CodeInterpreterStreamOutput2,
            CodeInterpreterStreamOutput3,
            CodeInterpreterStreamOutput4,
            CodeInterpreterStreamOutput5,
            CodeInterpreterStreamOutput6,
            CodeInterpreterStreamOutput7,
            CodeInterpreterStreamOutput8,
        ]
    ]
):
    root: Union[
        CodeInterpreterStreamOutput1,
        CodeInterpreterStreamOutput2,
        CodeInterpreterStreamOutput3,
        CodeInterpreterStreamOutput4,
        CodeInterpreterStreamOutput5,
        CodeInterpreterStreamOutput6,
        CodeInterpreterStreamOutput7,
        CodeInterpreterStreamOutput8,
    ]


class HarnessAgentCoreGatewayConfig(BaseModel):
    gatewayArn: str = Field(
        ...,
        pattern='^arn:aws(|-cn|-us-gov):bedrock-agentcore:[a-z0-9-]{1,20}:[0-9]{12}:gateway/([0-9a-z][-]?){1,48}-[a-z0-9]{10}$',
    )
    outboundAuth: Optional[HarnessGatewayOutboundAuth] = None


class HarnessToolConfiguration3(BaseModel):
    agentCoreGateway: HarnessAgentCoreGatewayConfig


class HarnessToolConfiguration(
    RootModel[
        Union[
            HarnessToolConfiguration1,
            HarnessToolConfiguration2,
            HarnessToolConfiguration3,
            HarnessToolConfiguration4,
            HarnessToolConfiguration5,
        ]
    ]
):
    root: Union[
        HarnessToolConfiguration1,
        HarnessToolConfiguration2,
        HarnessToolConfiguration3,
        HarnessToolConfiguration4,
        HarnessToolConfiguration5,
    ]


class HarnessTool(BaseModel):
    type: HarnessToolType
    name: Optional[str] = Field(
        default=None, max_length=64, min_length=1, pattern='^[a-zA-Z0-9_-]+$'
    )
    config: Optional[HarnessToolConfiguration] = None


class InvokeHarnessRequestContent(BaseModel):
    messages: List[HarnessMessage]
    model: Optional[HarnessModelConfiguration] = None
    systemPrompt: Optional[List[HarnessSystemContentBlock]] = None
    tools: Optional[List[HarnessTool]] = None
    skills: Optional[List[HarnessSkill]] = None
    allowedTools: Optional[List[AllowedTool]] = None
    maxIterations: Optional[int] = None
    maxTokens: Optional[int] = None
    timeoutSeconds: Optional[int] = None
    actorId: Optional[str] = None
