#!/usr/bin/env bash
# Runs ONLY on a newly created dedicated AL2023 ARM64 benchmark instance.
set -euo pipefail
umask 077
export HOME=/opt/juicefs-demo
mkdir -p "$HOME"
cd "$HOME"
# The deployment controller passes non-secret parameters only.
: "${AWS_REGION:?}" "${DATA_BUCKET:?}" "${DEPLOYMENT_ID:?}"
: "${ADMIN_SECRET_ARN:?}" "${TENANT_A_SECRET_ARN:?}" "${TENANT_B_SECRET_ARN:?}"
dnf install -y python3.12 python3.12-pip openssl tar gzip
python3.12 -m venv "$HOME/venv"
"$HOME/venv/bin/pip" install boto3==1.43.87 botocore==1.43.87
curl -fLsS --retry 3 -o juicefs.tar.gz https://github.com/juicedata/juicefs/releases/download/v1.4.1/juicefs-1.4.1-linux-arm64.tar.gz
printf '%s\n' '1015ade83a7a93180a29f6c93ee5780a3eda52522331934ef2ef0cc0921995fd  juicefs.tar.gz' | sha256sum -c -
tar -xzf juicefs.tar.gz juicefs
curl -fLsS --retry 3 -o mc https://dl.min.io/client/mc/release/linux-arm64/archive/mc.RELEASE.2021-04-22T17-40-00Z
# Digest pinned from the official archive used by the successful local TLS/IAM smoke test.
printf '%s\n' '23c98c585da3b3c6587445ce85e949d2618f80ab187641059007757ce3167df3  mc' | sha256sum -c -
chmod 700 juicefs mc
./juicefs version
./mc --version

# SQLite on encrypted EBS: deliberately single-node demo, not HA metadata.
META_URL="sqlite3://$HOME/metadata.db"
./juicefs format --storage s3 --bucket "https://${DATA_BUCKET}.s3.${AWS_REGION}.amazonaws.com" "$META_URL" shared-demo

TOKEN=$(curl -fsS -X PUT -H 'X-aws-ec2-metadata-token-ttl-seconds: 60' http://169.254.169.254/latest/api/token)
PRIVATE_IP=$(curl -fsS -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/local-ipv4)
export PRIVATE_IP
mkdir -p "$HOME/.minio/certs" "$HOME/cache-initial"
openssl req -x509 -newkey rsa:2048 -nodes -days 7 \
  -keyout "$HOME/.minio/certs/private.key" -out "$HOME/.minio/certs/public.crt" \
  -subj /CN=juicefs-demo -addext "subjectAltName=IP:${PRIVATE_IP},IP:127.0.0.1,DNS:localhost"

"$HOME/venv/bin/python" - <<'PY'
import json, os
from pathlib import Path
import boto3
home = Path(os.environ['HOME'])
sm = boto3.client('secretsmanager', region_name=os.environ['AWS_REGION'])
secret = json.loads(sm.get_secret_value(SecretId=os.environ['ADMIN_SECRET_ARN'])['SecretString'])
(home / 'gateway.env').write_text('MINIO_ROOT_USER=' + secret['AccessKeyId'] + '\nMINIO_ROOT_PASSWORD=' + secret['SecretAccessKey'] + '\n')
# Credentials are generated by the controller; never printed or returned via SSM.
PY

cat > /etc/systemd/system/juicefs-demo.service <<EOF
[Unit]
Description=Disposable JuiceFS benchmark gateway
After=network-online.target
Wants=network-online.target
[Service]
User=root
Environment=HOME=$HOME
Environment=AWS_REGION=$AWS_REGION
EnvironmentFile=$HOME/gateway.env
WorkingDirectory=$HOME
ExecStart=$HOME/juicefs gateway --multi-buckets --object-meta --keep-etag --no-banner --cache-dir $HOME/cache-initial --cache-size 1024 --refresh-iam-interval 1s sqlite3://$HOME/metadata.db 0.0.0.0:9000
Restart=on-failure
[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable --now juicefs-demo
for attempt in $(seq 1 60); do
  if curl -fsS --cacert "$HOME/.minio/certs/public.crt" https://127.0.0.1:9000/minio/health/live >/dev/null; then break; fi
  sleep 2
done
curl -fsS --cacert "$HOME/.minio/certs/public.crt" https://127.0.0.1:9000/minio/health/live >/dev/null

"$HOME/venv/bin/python" - <<'PY'
import json, os, subprocess
from pathlib import Path
import boto3
from botocore.config import Config
home = Path(os.environ['HOME'])
sm = boto3.client('secretsmanager', region_name=os.environ['AWS_REGION'])
admin = json.loads(sm.get_secret_value(SecretId=os.environ['ADMIN_SECRET_ARN'])['SecretString'])
cert = (home / '.minio/certs/public.crt').read_text()
# mc trusts the same demo CA, with TLS verification enabled.
ca = home / '.mc/certs/CAs'
ca.mkdir(parents=True, exist_ok=True)
(ca / 'demo.crt').write_text(cert)
def mc(*args):
    result = subprocess.run([str(home / 'mc'), *args], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    if result.returncode:
        raise RuntimeError('mc administration failed; sensitive command arguments suppressed')
mc('alias', 'set', 'local', 'https://127.0.0.1:9000', admin['AccessKeyId'], admin['SecretAccessKey'])
client = boto3.client('s3', endpoint_url='https://127.0.0.1:9000', region_name=os.environ['AWS_REGION'],
    aws_access_key_id=admin['AccessKeyId'], aws_secret_access_key=admin['SecretAccessKey'],
    verify=str(home / '.minio/certs/public.crt'),
    config=Config(signature_version='s3v4', s3={'addressing_style':'path'}, request_checksum_calculation='when_required'))
for tenant, variable in [('tenant-a', 'TENANT_A_SECRET_ARN'), ('tenant-b', 'TENANT_B_SECRET_ARN')]:
    record = json.loads(sm.get_secret_value(SecretId=os.environ[variable])['SecretString'])
    credentials = record['credentials']
    client.create_bucket(Bucket=tenant)
    policy = {'Version':'2012-10-17','Statement':[
        {'Effect':'Allow','Action':['s3:ListBucket'],'Resource':[f'arn:aws:s3:::{tenant}'],
         'Condition':{'StringLike':{'s3:prefix':['bench/*']}}},
        {'Effect':'Allow','Action':['s3:GetObject','s3:PutObject','s3:DeleteObject'],
         'Resource':[f'arn:aws:s3:::{tenant}/bench/*']}]}
    policy_path = home / (tenant + '-policy.json')
    policy_path.write_text(json.dumps(policy))
    mc('admin','user','add','local',credentials['AccessKeyId'],credentials['SecretAccessKey'])
    mc('admin','policy','add','local',tenant,str(policy_path))
    mc('admin','policy','set','local',tenant,'user='+credentials['AccessKeyId'])
    record.update(endpoint=f"https://{os.environ['PRIVATE_IP']}:9000", ca_pem=cert)
    sm.put_secret_value(SecretId=os.environ[variable], SecretString=json.dumps(record))
print('Gateway configured: TLS enabled; two tenant users; writeback disabled; SQLite metadata on EBS.')
PY
